1.10.2 turtle power
Tropicraft/Tropicraft pull request #195
Opened 2017-11-05 15:55 UTC by okushama

2017-11-06 04:14 UTC, Corosauce requested changes
Nice touch with the riding how it lets you control or they take control. Spawned logs of turtles, seems performant. Aside from the world time issue all seems good.

2017-11-06 04:14 UTC, Corosauce commented on src/main/java/net/tropicraft/core/common/entity/underdasea/EntitySeaTurtle.java
> +				&& world.getWorldTime() > 13000L && world.getWorldTime() < 23000L) {
This wouldnt trigger after the first night in world, suggestion: (worldTime % 24000)

2017-11-06 04:26 UTC, Corosauce approved these changes
:+1:

2017-11-07 00:22 UTC, Cojomax99 approved these changes
🐢

2017-11-07 01:49 UTC, merged