Added generated loot tables for living entities
Tropicraft/Tropicraft pull request #380
Opened 2020-10-24 20:08 UTC by ramou

* Fixed #379
  * iguana's drop leather and scales
  * frogs (all, not just green, sadly) dro poison frog skin
  * dolphins and sharks drop Tropical Fertilizer
  * Starfish and turtles drop their respective shells
  * Marlins drop fresh marlin
  * River Sardines, Tropical Fish and Piranahs drop raw fish
  * Sea Urchin drop Roe (no measure for age)
  * Eagle Rays drop Raw Eagle Ray
  * Man'o'War drops slime balls

2020-10-25 16:56 UTC, tterrag1098 requested changes

2020-10-25 16:56 UTC, tterrag1098 commented on src/main/java/net/tropicraft/core/common/data/TropicraftLootTableProvider.java
> +    }
Inconsistent indentation all over here

2020-10-25 16:56 UTC, tterrag1098 commented on src/main/java/net/tropicraft/core/common/data/TropicraftLootTableProvider.java
> +    	public void registerFrogLoot() {
This method should be made more reusable or just inlined into the above code, not much point in defining a method that can only be used once.

2020-10-25 16:56 UTC, tterrag1098 commented on src/main/java/net/tropicraft/core/common/data/TropicraftLootTableProvider.java
> +    									new NBTPredicate(Util.make(new CompoundNBT(), c -> c.putInt("Type", TreeFrogEntity.Type.GREEN.ordinal())))));
The indentation nesting here is a bit excessive
```suggestion
    	private static final ILootCondition.IBuilder GREEN = 
    			EntityHasProperty.builder(LootContext.EntityTarget.THIS, EntityPredicate.Builder.create()
    			    .flags(new EntityFlagsPredicate(null, null, null, null, false))
    			    .nbt(new NBTPredicate(Util.make(new CompoundNBT(), c -> c.putInt("Type", TreeFrogEntity.Type.GREEN.ordinal())))));
```

2020-10-25 16:56 UTC, tterrag1098 commented on src/main/java/net/tropicraft/core/common/data/TropicraftLootTableProvider.java
> +		public <T extends LivingEntity> void registerMinimalLootTable(RegistryObject<EntityType<T>> entity) {
Maybe just call this `noDrops` ?

2020-10-25 16:56 UTC, tterrag1098 commented on src/main/java/net/tropicraft/core/common/data/TropicraftLootTableProvider.java
> +		}
These methods could use more distinct names, such as `dropItem`, `dropItemWithEnchantBonus`, etc.

2020-10-25 16:56 UTC, tterrag1098 commented on src/main/java/net/tropicraft/core/common/data/TropicraftLootTableProvider.java
> +    	public void registerCreeperLoot() {
Again, could be inlined or made reusable.

2020-10-25 17:26 UTC, ramou commented
I'll have to remember how to change eclipse to use spaces instead of tabs, but I think I've made it consistent with the previous code at the bottom. I've incorporated all other suggestions, though didn't come up with anything better for `dropItemsWithEnchantBonus` when the single item isn't affected by enchantments but the multiple ones are..

2021-12-30 13:13 UTC, Gegy commented
Merged in https://github.com/Tropicraft/Tropicraft/commit/21cbd80413c5f1f78d53f34bfc166f2ec3bb8aba, tysm for the PR and apologies for the delay!

2021-12-30 13:13 UTC, closed without merging